// Code generated by protoc-gen-go-grpc. DO NOT EDIT.
// versions:
// - protoc-gen-go-grpc v1.5.1
// - protoc             v6.30.2
// source: server/server.proto

package server

import (
	context "context"

	grpc "google.golang.org/grpc"
	codes "google.golang.org/grpc/codes"
	status "google.golang.org/grpc/status"
)

// This is a compile-time assertion to ensure that this generated file
// is compatible with the grpc package it is being compiled against.
// Requires gRPC-Go v1.64.0 or later.
const _ = grpc.SupportPackageIsVersion9

const (
	FunctionRunnerService_Invoke_FullMethodName = "/FunctionRunnerService/Invoke"
)

// FunctionRunnerServiceClient is the client API for FunctionRunnerService service.
//
// For semantics around ctx use and closing/ending streaming RPCs, please refer to https://pkg.go.dev/google.golang.org/grpc/?tab=doc#ClientConn.NewStream.
type FunctionRunnerServiceClient interface {
	Invoke(ctx context.Context, in *InvokeRequest, opts ...grpc.CallOption) (*InvokeResult, error)
}

type functionRunnerServiceClient struct {
	cc grpc.ClientConnInterface
}

func NewFunctionRunnerServiceClient(cc grpc.ClientConnInterface) FunctionRunnerServiceClient {
	return &functionRunnerServiceClient{cc}
}

func (c *functionRunnerServiceClient) Invoke(ctx context.Context, in *InvokeRequest, opts ...grpc.CallOption) (*InvokeResult, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(InvokeResult)
	err := c.cc.Invoke(ctx, FunctionRunnerService_Invoke_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

// FunctionRunnerServiceServer is the server API for FunctionRunnerService service.
// All implementations must embed UnimplementedFunctionRunnerServiceServer
// for forward compatibility.
type FunctionRunnerServiceServer interface {
	Invoke(context.Context, *InvokeRequest) (*InvokeResult, error)
	mustEmbedUnimplementedFunctionRunnerServiceServer()
}

// UnimplementedFunctionRunnerServiceServer must be embedded to have
// forward compatible implementations.
//
// NOTE: this should be embedded by value instead of pointer to avoid a nil
// pointer dereference when methods are called.
type UnimplementedFunctionRunnerServiceServer struct{}

func (UnimplementedFunctionRunnerServiceServer) Invoke(context.Context, *InvokeRequest) (*InvokeResult, error) {
	return nil, status.Errorf(codes.Unimplemented, "method Invoke not implemented")
}
func (UnimplementedFunctionRunnerServiceServer) mustEmbedUnimplementedFunctionRunnerServiceServer() {}
func (UnimplementedFunctionRunnerServiceServer) testEmbeddedByValue()                               {}

// UnsafeFunctionRunnerServiceServer may be embedded to opt out of forward compatibility for this service.
// Use of this interface is not recommended, as added methods to FunctionRunnerServiceServer will
// result in compilation errors.
type UnsafeFunctionRunnerServiceServer interface {
	mustEmbedUnimplementedFunctionRunnerServiceServer()
}

func RegisterFunctionRunnerServiceServer(s grpc.ServiceRegistrar, srv FunctionRunnerServiceServer) {
	// If the following call pancis, it indicates UnimplementedFunctionRunnerServiceServer was
	// embedded by pointer and is nil.  This will cause panics if an
	// unimplemented method is ever invoked, so we test this at initialization
	// time to prevent it from happening at runtime later due to I/O.
	if t, ok := srv.(interface{ testEmbeddedByValue() }); ok {
		t.testEmbeddedByValue()
	}
	s.RegisterService(&FunctionRunnerService_ServiceDesc, srv)
}

func _FunctionRunnerService_Invoke_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(InvokeRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(FunctionRunnerServiceServer).Invoke(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: FunctionRunnerService_Invoke_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(FunctionRunnerServiceServer).Invoke(ctx, req.(*InvokeRequest))
	}
	return interceptor(ctx, in, info, handler)
}

// FunctionRunnerService_ServiceDesc is the grpc.ServiceDesc for FunctionRunnerService service.
// It's only intended for direct use with grpc.RegisterService,
// and not to be introspected or modified (even as a copy)
var FunctionRunnerService_ServiceDesc = grpc.ServiceDesc{
	ServiceName: "FunctionRunnerService",
	HandlerType: (*FunctionRunnerServiceServer)(nil),
	Methods: []grpc.MethodDesc{
		{
			MethodName: "Invoke",
			Handler:    _FunctionRunnerService_Invoke_Handler,
		},
	},
	Streams:  []grpc.StreamDesc{},
	Metadata: "server/server.proto",
}
